version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: students_db
    ports:
      - "5432:5432"
    restart: always

  student-app:
    image: iamsujata/student-app:latest
    container_name: student-service
    ports:
      - "8050:8050"
    depends_on:
      - postgres
    restart: always
